YAML preferences
eclipse/wildwebdeveloper pull request #930
Opened 2022-10-31 08:24 UTC by angelozerr

YAML preferences

Signed-off-by: azerr <azerr@redhat.com>

This PR provides all settings which manages YAML LS. I set to draft because I need to test if it works correctly.

2022-10-31 11:43 UTC, vrubezhny commented
@angelozerr Also, please, take a look at YAML JUnit tests - they fail probably because of changes in editor configuration:

```
Failures: 
  TestYaml.testSchemaExtensionPoint:91->testErrorFile:85 expected: <true> but was: <false>
  TestYaml.testSchemaExtensionPointUsingPlatformURL:96->testErrorFile:85 expected: <true> but was: <false>
```

2022-11-01 00:07 UTC, vrubezhny requested changes

2022-11-01 00:30 UTC, angelozerr commented on org.eclipse.wildwebdeveloper/plugin.properties
> +YAMLPreferencePage.name=YAML
fixed

2022-11-01 00:31 UTC, angelozerr commented on org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/ui/messages.properties
> +YAMLPreferencePage_maxItemsComputed=The maximum number of outline symbolsand folding\nregions computed (limited for performance reasons).
fixed

2022-11-01 00:31 UTC, angelozerr commented on org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/ui/messages.properties
> +YAMLCompletionPreferencePage_disableDefaultProperties=Globally set additionalProperties to false for all objects.\nSo if its true, no extra properties are allowed inside yaml.
fixed

2022-11-01 00:35 UTC, angelozerr commented on org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/ui/messages.properties
> +YAMLValidationPreferencePage_disableAdditionalProperties=Globally set additionalProperties to false for all objects. So if its true, no extra properties are allowed inside yaml.
Good catch, fixed.

2022-11-01 00:45 UTC, vrubezhny approved these changes

2022-11-01 01:06 UTC, angelozerr commented
Please note the YAML configuration must be improve to collect http and others ections.See https://github.com/eclipse/wildwebdeveloper/pull/930/files#diff-35f0eb9d34c1bd751f939c11d145d2dc8d81295432566dc74b5f882f2beb5d0cR42

2022-11-01 01:45 UTC, merged